version: '3.8'

services:
  tumsexy:
    image: ghcr.io/tum-dev/tum.sexy/sexy-server:latest
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tumsexy.entrypoints=web"
      - "traefik.http.routers.tumsexy.rule=Host(`tum.sexy`) || HostRegexp(`tum.sexy`, `{subdomain:[a-z0-9\-]+}.tum.sexy`)"
      - "traefik.http.routers.tumsexy.middlewares=webs-redirectscheme"

      - "traefik.http.routers.tumsexy-secure.entrypoints=webs"
      - "traefik.http.routers.tumsexy-secure.tls.certresolver=leacme"
      - "traefik.http.routers.tumsexy-secure.rule=Host(`tum.sexy`) || HostRegexp(`tum.sexy`, `{subdomain:[a-z0-9\-]+}.tum.sexy`)"
      - "traefik.http.services.tumsexy-secure.loadbalancer.server.port=80"
        
networks: 
  traefik_traefik:
    external: true
